export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const GET_UPDATE_KEY = "GET_UPDATE_KEY";
export const UPDATE_TODO_LABEL = "UPDATE_TODO_LABEL";
export const UPDATE_TODO_DONE = "UPDATE_TODO_DONE";
export const UPDATE_TODO_IMPORTANT = "UPDATE_TODO_IMPORTANT";
export const FETCH_TODO_LIST = "FETCH_TODO_LIST";
export const REQUEST_TODO_LIST = "REQUEST_TODO_LIST";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";

export const REGISTER_FORM = "REGISTER_FORM";

export const NAVIGATION_FILTER= "NAVIGATION_FILTER";

export const SEARCH_FORM = "SEARCH_FORM";

export const SHOW_ALERT = "SHOW_ALERT";

export const USER_TOKEN_ID = "USER_TOKEN_ID";
export const USER_ID = "USER_ID";

export const CURRENT_PAGE = "CURRENT_PAGE";
export const FILTERED_TODO_LIST = "FILTERED_TODO_LIST";

export const IS_AUTHENTICATED = "IS_AUTHENTICATED";
export const SING_USERNAME = "SING_USERNAME";
export const SING_PASSWORD = "SING_PASSWORD";
export const SING_CONFIRM_PASSWORD = "SING_CONFIRM_PASSWORD";

export const SHOW_MESSAGE = "SHOW_MESSAGE";